### ISSUE TITLE
Feature: Add `archetypePackage` helper variable with the full `package.json` from archetype.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/builder-init#18]
### Goals / Task

* [ ] Make `<archetype>[dev/|]/package.json` available as template data.

### Original Proposal

So that you can do this in `init/package.json`:

```
  "dependencies": {
    "builder": "~2.2.0",
    "builder-react-component": "^<%= archetypePackage.version %>"
  },
  "devDependencies": {
    "builder-react-component-dev": "^<%= archetypePackage.version %>",
    "chai": "^3.2.0",
    "mocha": "^2.3.3",
    "react": "^0.14.0",
    "react-addons-test-utils": "^0.14.0",
    "react-dom": "^0.14.0",
    "sinon": "^1.17.2",
    "sinon-chai": "^2.8.0"
  }
```

This probably obviates the need to implement https://github.com/FormidableLabs/builder-support/issues/7

/cc @chaseadamsio

**Comment by chaseadamsio** [comment]
:+1: if it's already there...we should use it that way...stupidly elegant. :)

**Comment by ryan-roemer** [comment]
@chaseadamsio -- Here's a strawman implementation / use: How's this sound?

#### `<archetype>/package.json`, `<archetype>/dev/package.json`

There is often a "chicken vs. egg" situation of an archetype under update vs.
the `init/` templates installed from and using the archetype. To help a variety
of situations, we provide a special `archetype` data variable with the
following data:

```
archetype:
  package       // `<archetype>/package.json` if it exists, else `{}`
  devPackage    // `<archetype>/dev/package.json` if it exists, else `{}`
```

This enables you to have "always correct" version values for `init/package.json`
by doing something like:

```js
{
  "dependencies": {
    "builder": "~2.2.0",
    "builder-react-component": "^<%= archetype.package.version || '0.1.2' %>"
  },
  "devDependencies": {
    "builder-react-component-dev": "^<%= archetype.devPackage.version || '0.1.2' %>",
  }
}
```

In your template content.
