### ISSUE TITLE
BUG: Only interpolate text file templates.

### ISSUE THREAD

**Issue by philholden** [FormidableLabs/builder-init#21]
PNGs in archetype get mangled by templating

**Comment by ryan-roemer** [comment]
Oh yeah, that's definitely an oversight in the template and approach. It processes everything thinking that anything is text. Which clearly is not the case! Do you think we should solve this with doing file metadata type inference? Or possibly file extension instead?

**Comment by ryan-roemer** [comment]
Researching file type inference libs. This one looks ok: https://github.com/sindresorhus/file-type

**Comment by ryan-roemer** [comment]
Would love to use https://github.com/mscdex/mmmagic but it requires a compiler just for a normal install. On my mac, it even hiccuped and died because I haven't blessed the command line tools yet with:

```
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
```
