### ISSUE TITLE
"builder-init builder-react-component" fails on Windows

### ISSUE THREAD

**Issue by LittleBrainz** [FormidableLabs/builder-init#27]
On my Windows 10 machine with node 5.6.0 & npm 3.6.0...

```
C:\Code> npm -g install builder-init
C:\Users\Stephen\AppData\Roaming\npm\builder-init -> C:\Users\Stephen\AppData\Roaming\npm\node_modules\builder-init\bin\builder-init.js
C:\Users\Stephen\AppData\Roaming\npm
`-- builder-init@0.2.1
```

All seems OK...

```
C:\Code\my-project> builder-init
Usage:

  builder-init [flags] <archetype>

Flags:
...
```

But...

```
C:\Code\my-project> builder-init builder-react-component
Error: spawn npm ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)
```

Have I done something wrong?

Kind regards,

Stephen

PS. Builder looks like it could be a serious time saver. Brilliant work!

**Comment by ryan-roemer** [comment]
@LittleBrainz -- I'll pull a windows VM and try it out, most likely over the weekend or next week and see what's up.

**Comment by ryan-roemer** [comment]
Confirmed. I have a reproduction in a VM. I'm going to try and dig in, but I'm on vacation for a week, so might be late next week before I have time to turn to this.

Offhand, guessing something weird with passing PATH / some environment variable down to the spawn of `npm` command...

**Comment by ryan-roemer** [comment]
Oh windows... So the awkward part is that `npm` is _not_ an executable on Windows, it's a script.

We need this change:

```
var proc = childProc.spawn("cmd", ["/c", ""npm", "pack", self.archetype], {
```

Here: https://github.com/FormidableLabs/builder-init/blob/master/lib/task.js#L157

I'll see if I can whip up a PR that auto detects and "does the right thing" based on detected architecture in the next two weeks.

**Comment by kgdiem** [comment]
I've experienced this today on Windows 10 w/ Powershell.  I was able to sucessfully init a project with WSL / Ubuntu on Windows

builder-init version: 0.5.1 
NPM version: 5.6.0
Node version: 8.9.1

Steps to reproduce: 
```
$ npm install -g builder-init
$ builder-init dash-components-archetype
```

Expected result was a prompt. I received this output: 
```
Error: spawn cmd ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by ryan-roemer** [comment]
@kgdiem -- Can you open this as a different issue? It's not the one I closed, which we fixed (it just has the same stack trace).

Also in the new issue can you try in old `cmd` shell instead of Powershell and report if that works? Thanks!

I had a win10 vm handy with node 6.11.3 and npm 3.10.10 and the above commands worked fine with `builder-init@0.5.1`.
