### ISSUE TITLE
Question: What happens if I update an archetype?

### ISSUE THREAD

**Issue by juliancoleman** [FormidableLabs/builder-init#46]
I guess I can answer my own question by putting this into practice, but I've just found this package and it's a bit late.

But what I would expect to have happen is when I push a new release of a builder-init archetype, I should also want to update other repos that are built on that archetype to reflect the new changes.

* do I just rerun `builder-init`?
* if so, do existing files get overwritten?
* do new files get created if they are added in a later update from the version of the archetype initially used to initialize the project?

Thanks a bunch in advance! Love the work you guys do at Formidable.

**Comment by ryan-roemer** [comment]
Thanks for the kind words!

`builder-init` is meant as a "one time scaffold" type thing. All the things aside from your projects substantive code (e.g., build, lint, test configurations, and devDependencies) should be placed in an archetype and _that_ should be upgraded -- which is as simple as a version bump after publishing.

Accordingly, `builder-init` will explicitly refuse to run in a non-empty directory, to provide a deterministic, sane method of building out. Updating files in place is such a complicated endeavor, and not particularly well-suited to automating, that we just completely avoid it :)
